# Kairos Symbiotic Interface Configuration
# Project Kairos - Autonomous Digital Organization
# Version: 2.0

# Database Configuration
database:
  host: localhost
  port: 5432
  database: kairos
  user: kairos
  password: kairos_password
  min_connections: 5
  max_connections: 20
  command_timeout: 60

# Redis Configuration
redis:
  host: localhost
  port: 6379
  db: 0
  password: null  # Set if Redis requires authentication

# GraphQL Server Configuration
graphql:
  host: 0.0.0.0
  port: 8000
  debug: false
  cors_origins:
    - "*"  # Configure properly for production
  rate_limit: 1000
  query_complexity_limit: 100

# gRPC Server Configuration
grpc:
  host: 0.0.0.0
  port: 50051
  max_workers: 100
  keepalive_time_ms: 30000
  keepalive_timeout_ms: 5000

# Security Configuration
security:
  api_key: kairos_production_key_change_me
  jwt_secret: kairos_jwt_secret_change_me
  rate_limit: 1000
  cors_enabled: true
  
# Logging Configuration
logging:
  level: INFO
  file: E:\kairos\logs\symbiotic_interface.log
  max_file_size: 100MB
  backup_count: 5

# Oracle Engine Configuration
oracle:
  simulation_workers: 4
  max_concurrent_simulations: 10
  default_confidence_threshold: 0.8
  prediction_cache_ttl: 300  # seconds

# Economy Engine Configuration
economy:
  initial_cc_balance: 1000.0
  transaction_fee: 0.01  # 1% transaction fee
  minimum_bid: 10.0
  maximum_cc_per_agent: 10000.0

# Health Monitoring Configuration
monitoring:
  health_check_interval: 30  # seconds
  metrics_collection_interval: 60  # seconds
  service_registry_ttl: 300  # seconds

# Performance Configuration
performance:
  connection_pool_size: 20
  redis_pool_size: 10
  worker_threads: 100
  max_query_depth: 10
  timeout_seconds: 30

# Feature Flags
features:
  enable_subscriptions: true
  enable_metrics_collection: true
  enable_service_discovery: true
  enable_causal_reasoning: true
  enable_oracle_predictions: true